SOURCES  = memory.c object.c pair.c obuffer.c string.c symbol.c \
           basichash.c integer.c  basiclist.c vector.c \
           miscobjects.c char.c charconv.c ucs4.c utf8.c \
           encoding.c vm.c procedure.c binding.c reference.c
#          ibuffer.c parser.c port.c